### ISSUE TITLE
Fel priser i lab1.tex för assignment 4?

### ISSUE THREAD

**Issue by oscarcederberg** [lunduniversity/webprog#10]
labs/lab1/lab1.tex:237-238
Priserna för assignment 4 verkar vara fel med 10kr.

Sallad + Kycklingfile + Bacon + Krutonger + Parmesan + Ceasardressing =
( 0,5   ×   10 )   +   ( 2   ×   10 )   +   ( 0,5   ×   10 )   +   ( 1   ×   5 )   +   ( 2   ×   5 )   +   ( 1   ×   5 ) = 50 (Med lite bacon)
( 0,5   ×   10 )   +   ( 2   ×   10 )   +   ( 1,5   ×   10 )   +   ( 1   ×   5 )   +   ( 2   ×   5 )   +   ( 1   ×   5 ) = 60 (Med extra bacon)
I labbinstruktionerna så står det 40kr och 50kr.

**Comment by cs-pan** [comment]
rätt, jag patchade igår men glömde göra push.
